### ISSUE TITLE
GuzzleHttp incompatible $httpBody creation in \SendinBlue\Client\Api\ContactsApi::createContactRequest

### ISSUE THREAD

**Issue by ktomk** [sendinblue/APIv3-php-library#160]
The `$httpBody` creation by `SendinBlue\Client\Api\ContactsApi->createContactRequest()` has uncaught errors when collaborating with **GuzzleHttp**:

> Method SendinBlue\Client\Model\CreateContact::__toString() must return a string value in .../vendor/guzzlehttp/psr7/src/Utils.php:341

Stack trace:
~~~
#0 .../vendor/guzzlehttp/psr7/src/Request.php(55): GuzzleHttp\Psr7\Utils::streamFor()
#1 .../vendor/sendinblue/api-v3-sdk/lib/Api/ContactsApi.php(965): GuzzleHttp\Psr7\Request->__construct()
#2 .../vendor/sendinblue/api-v3-sdk/lib/Api/ContactsApi.php(713): SendinBlue\Client\Api\ContactsApi->createContactRequest()
#3 .../vendor/sendinblue/api-v3-sdk/lib/Api/ContactsApi.php(695): SendinBlue\Client\Api\ContactsApi->createContactWithHttpInfo()
#4 .../file.php(376): SendinBlue\Client\Api\ContactsApi->createContact()
~~~

It looks like the contract on `__toString(): string` is broken in:

https://github.com/sendinblue/APIv3-php-library/blob/0b86513957d22c3fcd0598f5c961be2513f6c8d6/lib/Model/CreateContact.php#L463-L478

the return value from `json_encode` is not asserted at least.

Configuration info:
~~~
sendinblue/api-v3-sdk        v7.4.2             Official SendinBlue provided RESTFul API V3 php library
~~~

Additional Context:

* Create: https://github.com/sendinblue/APIv3-php-library/blob/0b86513957d22c3fcd0598f5c961be2513f6c8d6/lib/Api/ContactsApi.php#L883
* Pass: https://github.com/sendinblue/APIv3-php-library/blob/0b86513957d22c3fcd0598f5c961be2513f6c8d6/lib/Api/ContactsApi.php#L964-L969
* Collaborator: **SendinBlue\Client\Model**
* Affected: **SendinBlue\Client\Api\ContactsApi**
* (Cross-Reference, Similar-Error) https://github.com/sendinblue/APIv3-php-library/issues/133

**Comment by ktomk** [comment]
**Cause**

Cause of the error was a string that was not UTF-8 encoded.

**Discussion**

As strings in PHP are binary this error picture is entirely possible and most likely will happen under more unforeseen circumstances (as commonly UTF-8 is a given in the library usage-context like PHP, JSON-REST-API, HTTP, HTML nowadays).

It then could benefit from earlier/better error reporting.

Someone may want to consider a version check for PHP 7.4 and then call `json_encode()` with flag `JSON_THROW_ON_ERROR` within this (and perhaps similar) `::__toString()` implementation (the fix should cover the whole bug-cluster if there is some, have not checked, compare #133 ).

PHP 7.4 version constraint is due to the ability to throw within `::__toString()` which is not possible before.

* https://wiki.php.net/rfc/json_throw_on_error (PHP 7.3)
* https://wiki.php.net/rfc/tostring_exceptions (PHP 7.4)

**Comment by ktomk** [comment]
I have no information about the projects policy on such kind of issues, therefore closing as we could solve it at the root cause preventing the uncaught error entirely.

We now treat the libraries behaviour as undefined for non-UTF8-string input and check our strings first.

It should go without saying that anyone can freely re-open and make use of this contribution whenever they see fit and we do see, that there would have been benefit for us if the json_encoding would have been throwing exceptions at the time before this report.
