### ISSUE TITLE
Notice: Undefined index: version

### ISSUE THREAD

**Issue by Linkinou** [sendinblue/APIv3-php-library#206]
Hello !

I've been facing an issue that occurs randomly when we try to create a new contact in sendinblue.

The error : `Notice: Undefined index: version`

It seems coming from `Configuration::getDefaultConfiguration()->setApiKey('api-key', $mailApiKey);` 
It tries to retrieve the PHP version from the globals : `$this->userAgent = 'sendinblue_clientAPI/v' . $GLOBALS['version'] . '/php'; `

But I don't understand why and what can we do about it.
Because this leads to our users not being added to our sendinblue contacts list.

Any ideas/suggestions are welcome

**Comment by preetishishodia7** [comment]
Hi @Linkinou

Can you please share a sample script that you are using ?

**Comment by Linkinou** [comment]
Hi @preetishishodia7 
Sorry for the late response.

Here our MailService : https://pastebin.com/0YMJ2iZm

We simply use "CreateContact" during a registration or in a newsletter registration.

For example for our newsletter (https://ozzak.fr/bientot-chez-toi)
`
$mailService->createContact(
                $waitingList->email,
                '',
                '',
                $waitingList->postalCode,
                new \DateTime(),
                'B2C',
                true,
                [13]
            );
`

It appears that the problem is triggered randomly because the error doesn't occur every time. 

I dont see why $GLOBALS['version'] could be, sometimes, undefined.

**Comment by Linkinou** [comment]
Hello @preetishishodia7 

Any news on this ?

Thank you

**Comment by preetishishodia7** [comment]
Hi @Linkinou will update you soon

**Comment by preetishishodia7** [comment]
Hi @Linkinou I'm not able to reproduce this at my end. can you please provide the Error trace? And which PHP version are you using?

**Comment by Linkinou** [comment]
Hi @preetishishodia7 , thank you for looking into it. 

Here the stacktrace :

`ErrorException: Notice: Undefined index: version
#12 /vendor/sendinblue/api-v3-sdk/lib/Configuration.php(116): SendinBlue\Client\Configuration::__construct
#11 /vendor/sendinblue/api-v3-sdk/lib/Configuration.php(371): SendinBlue\Client\Configuration::getDefaultConfiguration
#10 /src/Service/MailService.php(32): App\Service\MailService::__construct
#9 /var/cache/prod/ContainerNKuFC6t/getMailServiceService.php(20): ContainerNKuFC6t\getMailServiceService::do
#8 /var/cache/prod/ContainerNKuFC6t/App_KernelProdContainer.php(192): ContainerNKuFC6t\App_KernelProdContainer::load
#7 /vendor/symfony/dependency-injection/Container.php(422): Symfony\Component\DependencyInjection\Container::getService
#6 /vendor/symfony/dependency-injection/Argument/ServiceLocator.php(42): Symfony\Component\DependencyInjection\Argument\ServiceLocator::get
#5 /vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php(77): Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver::resolve
#4 /vendor/symfony/http-kernel/Controller/ArgumentResolver.php(58): Symfony\Component\HttpKernel\Controller\ArgumentResolver::getArguments
#3 /vendor/symfony/http-kernel/HttpKernel.php(144): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#0 /public/index.php(20): null`

And we're using PHP 7.4.28

**Comment by preetishishodia7** [comment]
Hi @Linkinou 
We are unable to reproduce this at our end, we need some more information to debug further.
Can you please tell us which PHP SDK version you are using? And also if you can share sample script which giving error. 
Thanks!

**Comment by preetishishodia7** [comment]
Hi, 
We are closing this issue due to inactivity since 11 days.
